# Generated by Django 4.1.1 on 2022-11-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_category', models.TextField(max_length=80)),
                ('codigo', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=40)),
                ('name_client', models.TextField(max_length=80)),
                ('password', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id_game', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_game', models.TextField(max_length=60)),
                ('price', models.CharField(max_length=8)),
                ('category', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id_sales', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_client', models.IntegerField()),
                ('id_game', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('value', models.IntegerField()),
                ('total_Sale', models.IntegerField()),
            ],
        ),
    ]
